# Generated by Django 2.2.6 on 2019-11-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 0, 0)),
            preserve_default=False,
        ),
    ]
